import os


# Mensagem inicial
INITIAL_MESSAGE = 'OLÁ, EU SOU O UGU! ESTOU AQUI PARA TE AJUDAR!'

# Mensagem de despedida
FAREWELL_MESSAGE = (f'OBRIGADO POR UTILIZAR O CHAT UFU, ESPERO TER AJUDADO!\nVOLTE SEMPRE QUE PRECISAR, BASTA'
                    f' ME MANDAR UM "OLÁ" OU UM "OI" PARA ME ATIVAR NOVAMENTE =D')

# Mensagem de opção inválida
INVALID_OPTION = 'OPÇÃO INVÁLIDA! DIGITE UMA OPÇÃO VÁLIDA!'

# Títulos dos menus
HOME_MENU_TITLE = 'MENU PRINCIPAL'
COURSE_INFORMATION_TITLE = 'INFORMAÇÕES SOBRE O CURSO'
BCC_INFOS_TITLE = f'{COURSE_INFORMATION_TITLE}: CIÊNCIA DA COMPUTAÇÃO'
BSI_INFOS_TITLE = f'{COURSE_INFORMATION_TITLE}: SISTEMAS DE INFORMAÇÃO'
CALENDER_TITLE = 'CALENDÁRIO ACADÊMICO'
UFU_SERVICES_TITLE = 'SERVIÇOS DA UFU'
LOCATION_TITLE = 'LOCALIZAÇÃO'
CLASSROOMS_TITLE = 'BLOCOS DE AULAS'
EVENTS_TITLE = 'EVENTOS'
TUTORIALS_TITLE = 'GUIAS E TUTORIAIS'

# Menu ID's
HOME_ID = 1
COURSE_INFORMATION_ID = '2'
CALENDER_ID = '3'
UFU_SERVICES_ID = '4'
LOCATION_ID = '5'
EVENTS_ID = '6'
TUTORIALS_ID = '7'
BCC_INFOS_ID = '8'
BSI_INFOS_ID = '9'
CLASSROOMS_ID = '10'
BCC_GRID_ID = '11'
BCC_PROFESSORS_ID = '12'
BCC_DISCIPLINES_ID = '13'
BSI_GRID_ID = '14'
BSI_PROFESSORS_ID = '15'
BSI_DISCIPLINES_ID = '16'
SERVICES_RU_ID = '17'
SERVICES_INTERCAMPI_ID = '18'
SERVICES_LIBRARY_ID = '19'
SERVICES_HEALTH_ID = '20'
LOCATION_BCC_ID = '21'
LOCATION_BSI_ID = '22'
LOCATION_DACOMP_ID = '23'
LOCATION_ATLETICA_ID = '24'
LOCATION_COMPUTARIA_ID = '25'
CLASSROOMS_1B_ID = '26'
CLASSROOMS_3Q_ID = '27'
CLASSROOMS_5R_ID = '28'

LINK_TITLES = {
    HOME_ID: HOME_MENU_TITLE,
    COURSE_INFORMATION_ID: COURSE_INFORMATION_TITLE,
    UFU_SERVICES_ID: UFU_SERVICES_TITLE,
    LOCATION_ID: LOCATION_TITLE,
    BCC_INFOS_ID: BCC_INFOS_TITLE,
    BSI_INFOS_ID: BSI_INFOS_TITLE,
    CLASSROOMS_ID: CLASSROOMS_TITLE
}

# Opções de menus
CLOSE_OPTION = '0'

# Menu Principal
COURSE_INFORMATION_OPTION = '1'
CALENDER_OPTION = '2'
UFU_SERVICES_OPTION = '3'
LOCATION_OPTION = '4'
EVENTS_OPTION = '5'
TUTORIALS_OPTION = '6'

HOME = {
    COURSE_INFORMATION_OPTION: ('INFORMAÇÕES DO CURSO', COURSE_INFORMATION_ID),
    CALENDER_OPTION: ('CALENDÁRIO ACADÊMICO', CALENDER_ID),
    UFU_SERVICES_OPTION: ('SERVIÇOS DA UFU', UFU_SERVICES_ID),
    LOCATION_OPTION: ('LOCALIZAÇÃO', LOCATION_ID),
    EVENTS_OPTION: ('EVENTOS', EVENTS_ID),
    TUTORIALS_OPTION: ('GUIAS E TUTORIAIS', TUTORIALS_ID),
    CLOSE_OPTION: ('SAIR', None)
}

# Escolha o curso
BCC_OPTION = '1'
BSI_OPTION = '2'

COURSES_MENU = {
    BCC_OPTION: ('CIÊNCIA DA COMPUTAÇÃO', BCC_INFOS_ID),
    BSI_OPTION: ('SISTEMAS DE INFORMAÇÃO', BSI_INFOS_ID),
    CLOSE_OPTION: ('MENU PRINCIPAL', HOME_ID)
}

# Infos de BCC
BCC_GRID_OPTION = '1'
BCC_PROFESSORS_OPTION = '2'
BCC_DISCIPLINES_OPTION = '3'

BCC_INFOS = {
    BCC_GRID_OPTION: ('GRADE DO CURSO', BCC_GRID_ID),
    BCC_PROFESSORS_OPTION: ('CONTATO DOS PROFESSORES', BCC_PROFESSORS_ID),
    BCC_DISCIPLINES_OPTION: ('DISCIPLINAS', BCC_DISCIPLINES_ID),
    CLOSE_OPTION: ('MENU PRINCIPAL', HOME_ID)
}

# Infos de BSI
BSI_GRID_OPTION = '1'
BSI_PROFESSORS_OPTION = '2'
BSI_DISCIPLINES_OPTION = '3'

BSI_INFOS = {
    BSI_GRID_OPTION: ('GRADE DO CURSO', BSI_GRID_ID),
    BSI_PROFESSORS_OPTION: ('CONTATO DOS PROFESSORES', BSI_PROFESSORS_ID),
    BSI_DISCIPLINES_OPTION: ('DISCIPLINAS', BSI_DISCIPLINES_ID),
    CLOSE_OPTION: ('MENU PRINCIPAL', HOME_ID)
}

# Serviços UFU
SERVICES_RU_OPTION = '1'
SERVICES_INTERCAMPI_OPTION = '2'
SERVICES_LIBRARY_OPTION = '3'
SERVICES_HEALTH_OPTION = '4'

SERVICES = {
    SERVICES_RU_OPTION: ('RESTAURANTE UNIVERSITÁRIO', SERVICES_RU_ID),
    SERVICES_INTERCAMPI_OPTION: ('INTERCAMPI', SERVICES_INTERCAMPI_ID),
    SERVICES_LIBRARY_OPTION: ('BIBLIOTECA', SERVICES_LIBRARY_ID),
    SERVICES_HEALTH_OPTION: ('SERVIÇOS DE SAÚDE', SERVICES_HEALTH_ID),
    CLOSE_OPTION: ('MENU PRINCIPAL', HOME_ID)
}

# Localização
LOCATION_BCC_OPTION = '1'
LOCATION_BSI_OPTION = '2'
LOCATION_DACOMP_OPTION = '3'
LOCATION_ATLETICA_OPTION = '4'
LOCATION_COMPUTARIA_OPTION = '5'
LOCATION_BLOCOS_OPTION = '6'

LOCATIONS = {
    LOCATION_BCC_OPTION: ('SECRETARIA DO CURSO DE CIÊNCIA DE COMPUTAÇÃO', LOCATION_BCC_ID),
    LOCATION_BSI_OPTION: ('SECRETARIA DO CURSO DE SISTEMAS DE INFORMAÇÃO', LOCATION_BSI_ID),
    LOCATION_DACOMP_OPTION: ('DACOMP (DIRETÓRIO ACADÊMICO ALAN TURING)', LOCATION_DACOMP_ID),
    LOCATION_ATLETICA_OPTION: ('ATLÉTICA DA COMPUTAÇÃO', LOCATION_ATLETICA_ID),
    LOCATION_COMPUTARIA_OPTION: ('BATERIA COMPUTARIA', LOCATION_COMPUTARIA_ID),
    LOCATION_BLOCOS_OPTION: ('BLOCOS DE AULAS', CLASSROOMS_ID),
    CLOSE_OPTION: ('MENU PRINCIPAL', HOME_ID)
}

# Localização dos blocos
CLASSROOMS_1B_OPTION = '1'
CLASSROOMS_3Q_OPTION = '2'
CLASSROOMS_5R_OPTION = '3'
CLASSROOMS = {
    CLASSROOMS_1B_OPTION: ('BLOCO 1B', CLASSROOMS_1B_ID),
    CLASSROOMS_3Q_OPTION: ('BLOCO 3Q', CLASSROOMS_3Q_ID),
    CLASSROOMS_5R_OPTION: ('BLOCO 5R', CLASSROOMS_5R_ID),
    CLOSE_OPTION: ('MENU PRINCIPAL', HOME_ID)
}

# NODES & LEAFS
NODES = {
    HOME_ID: HOME,
    COURSE_INFORMATION_ID: COURSES_MENU,
    UFU_SERVICES_ID: SERVICES,
    LOCATION_ID: LOCATIONS,
    BCC_INFOS_ID: BCC_INFOS,
    BSI_INFOS_ID: BSI_INFOS,
    CLASSROOMS_ID: CLASSROOMS
}

TUTORIAL = (f'GUIA{os.linesep}'
            f'OLÁ, SAIBA COMO USAR O UGU!{os.linesep}{os.linesep}'
            f'Verifique no Menu quais das informações você deseja saber, após isso basta digitar um único digito da opç'
            f'ão, por exemplo, apenas o número:{os.linesep}{os.linesep}'
            f'1{os.linesep}{os.linesep}'
            f'Com isso o UGU irá te retornar todas as informações para que você possa entender sobre o tema.'
            f'{os.linesep}'
            f'Um submenu pode aparecer solicitando que você digite novamente uma opção desejada, assim da mesma forma c'
            f'omo fez no ínicio, basta digitar um único digito da opção, por exemplo, apenas o número:{os.linesep}'
            f'{os.linesep}'
            f'2{os.linesep}{os.linesep}'
            f'Para sair e finalizar ou solicitar uma nova informação, você deve apenas digitar o número 0.')

LEAFS = {
    CALENDER_ID: 'CALENDÁRIO ACADÊMICO - http://www.prograd.ufu.br/central-de-conteudos/documentos/calendario',
    EVENTS_ID: 'EVENTOS - https://eventos.ufu.br',
    TUTORIALS_ID: TUTORIAL,
    BCC_GRID_ID: 'GRADE DE BCC - https://facom.ufu.br/system/files/conteudo/fluxo_curricular_bcc_-_2023-1_1_0.pdf',
    BCC_PROFESSORS_ID: 'PROFESSORES DE BCC - https://facom.ufu.br/system/files/conteudo/e-mail_professores_2023-1.pdf',
    BCC_DISCIPLINES_ID: 'DISCIPLINAS DE BCC - https://facom.ufu.br/graduacao/ciencia-da-computacao-campus-santa-monica/'
                        'fichas-de-disciplina/curriculo-2023-1',
    BSI_GRID_ID: 'GRADE DE BSI - https://facom.ufu.br/system/files/conteudo/fluxograma_curricular_do_bacharelado_em_si_'
                 '0.pdf',
    BSI_PROFESSORS_ID: 'PROFESSORES DE BSI - https://facom.ufu.br/system/files/conteudo/e-mail_professores_2023-1.pdf',
    BSI_DISCIPLINES_ID: 'DISCIPLINAS DE BSI - https://facom.ufu.br/graduacao/bsi-santamonica/fichas-de-disciplinas-curr'
                        'iculo-2022-2',
    SERVICES_RU_ID: 'RESTAURANTE UNIVERSITÁRIO (RU) - https://maps.app.goo.gl/e1h7jsF9aEeEZ1BK7',
    SERVICES_INTERCAMPI_ID: 'INTERCAMPI - http://www.proae.ufu.br/intercampi',
    SERVICES_LIBRARY_ID: 'BIBLIOTECA SANTA MÔNICA - https://maps.app.goo.gl/Rpy4KYNsKhqQhPPA8',
    SERVICES_HEALTH_ID: 'SAÚDE NA UFU - http://www.proae.ufu.br/disau',
    LOCATION_BCC_ID: 'COORDENAÇÃO BCC - BLOCO 1A - SALA 228 - https://maps.app.goo.gl/gjmb5gnSaSj5WYT37',
    LOCATION_BSI_ID: 'COORDENAÇÃO BSI - BLOCO 1A - SALA 230 - https://maps.app.goo.gl/gjmb5gnSaSj5WYT37',
    LOCATION_DACOMP_ID: 'DACOMP - Bloco 1B - Sala107A https://maps.app.goo.gl/pAyG19Xi1K543iQo6',
    LOCATION_ATLETICA_ID: 'Atlética Computação Bloco 1B Sala 101 -  https://maps.app.goo.gl/65WcFkjy76tz1tLz5',
    LOCATION_COMPUTARIA_ID: 'Bateria Computaria - Bloco 1B - Sala 107B https://maps.app.goo.gl/65WcFkjy76tz1tLz5',
    CLASSROOMS_1B_ID: 'Bloco 1B - https://maps.app.goo.gl/ih9vQTeGRAcEGwYX9',
    CLASSROOMS_3Q_ID: 'Bloco 3Q - https://maps.app.goo.gl/4n4JB7sKfoqdPDXx7',
    CLASSROOMS_5R_ID: 'Bloco 5R-A - https://maps.app.goo.gl/W69kgQUS8AFQn3Pd9'
}
