import os


# Mensagem inicial
INITIAL_MESSAGE = 'OLÁ, EU SOU O UGU! ESTOU AQUI PARA TE AJUDAR!'

# Mensagem de despedida
FAREWELL_MESSAGE = (f'OBRIGADO POR UTILIZAR O CHAT UFU, ESPERO TER AJUDADO!{os.linesep}VOLTE SEMPRE QUE PRECISAR, BASTA'
                    f' ME MANDAR UM "OLÁ" OU UM "OI" PARA ME ATIVAR NOVAMENTE =D')

# Mensagem de opção inválida
INVALID_OPTION = 'OPÇÃO INVÁLIDA! DIGITE UMA OPÇÃO VÁLIDA!'

# Títulos dos menus
HOME_MENU_TITLE = 'MENU PRINCIPAL'
COURSE_INFORMATION_TITLE = 'INFORMAÇÕES SOBRE O CURSO'
BCC_INFOS_TITLE = f'{COURSE_INFORMATION_TITLE}: CIÊNCIA DA COMPUTAÇÃO'
BSI_INFOS_TITLE = f'{COURSE_INFORMATION_TITLE}: SISTEMAS DE INFORMAÇÃO'
CALENDER_TITLE = 'CALENDÁRIO ACADÊMICO'
UFU_SERVICES_TITLE = 'SERVIÇOS DA UFU'
LOCATION_TITLE = 'LOCALIZAÇÃO'
CLASSROOMS_TITLE = 'BLOCOS DE AULAS'
EVENTS_TITLE = 'EVENTOS'
TUTORIALS_TITLE = 'GUIAS E TUTORIAIS'

# Menu ID's
HOME_ID = '1'
COURSE_INFORMATION_ID = '2'
CALENDER_ID = '3'
UFU_SERVICES_ID = '4'
LOCATION_ID = '5'
EVENTS_ID = '6'
TUTORIALS_ID = '7'
BCC_INFOS_ID = '8'
BSI_INFOS_ID = '9'
CLASSROOMS_ID = '10'
BCC_GRID_ID = '11'
BCC_PROFESSORS_ID = '12'
BCC_DISCIPLINES_ID = '13'
BSI_GRID_ID = '14'
BSI_PROFESSORS_ID = '15'
BSI_DISCIPLINES_ID = '16'
SERVICES_RU_ID = '17'
SERVICES_INTERCAMPI_ID = '18'
SERVICES_LIBRARY_ID = '19'
SERVICES_HEALTH_ID = '20'
LOCATION_BCC_ID = '21'
LOCATION_BSI_ID = '22'
LOCATION_DACOMP_ID = '23'
LOCATION_ATLETICA_ID = '24'
LOCATION_COMPUTARIA_ID = '25'
CLASSROOMS_1B_ID = '26'
CLASSROOMS_3Q_ID = '27'
CLASSROOMS_5R_ID = '28'

LINK_TITLES = {
    HOME_ID: HOME_MENU_TITLE,
    COURSE_INFORMATION_ID: COURSE_INFORMATION_TITLE,
    UFU_SERVICES_ID: UFU_SERVICES_TITLE,
    LOCATION_ID: LOCATION_TITLE,
    BCC_INFOS_ID: BCC_INFOS_TITLE,
    BSI_INFOS_ID: BSI_INFOS_TITLE,
    CLASSROOMS_ID: CLASSROOMS_TITLE
}

# Opções de menus
CLOSE_OPTION = '0'

# Menu Principal
COURSE_INFORMATION_OPTION = '1'
CALENDER_OPTION = '2'
UFU_SERVICES_OPTION = '3'
LOCATION_OPTION = '4'
EVENTS_OPTION = '5'
TUTORIALS_OPTION = '6'

HOME = {
    COURSE_INFORMATION_OPTION: ('INFORMAÇÕES DO CURSO', COURSE_INFORMATION_ID),
    CALENDER_OPTION: ('CALENDÁRIO ACADÊMICO', CALENDER_ID),
    UFU_SERVICES_OPTION: ('SERVIÇOS DA UFU', UFU_SERVICES_ID),
    LOCATION_OPTION: ('LOCALIZAÇÃO', LOCATION_ID),
    EVENTS_OPTION: ('EVENTOS', EVENTS_ID),
    TUTORIALS_OPTION: ('GUIAS E TUTORIAIS', TUTORIALS_ID),
    CLOSE_OPTION: ('SAIR', None)
}

# Escolha o curso
BCC_OPTION = '1'
BSI_OPTION = '2'

COURSES_MENU = {
    BCC_OPTION: ('CIÊNCIA DA COMPUTAÇÃO', BCC_INFOS_ID),
    BSI_OPTION: ('SISTEMAS DE INFORMAÇÃO', BSI_INFOS_ID),
    CLOSE_OPTION: ('MENU PRINCIPAL', HOME_ID)
}

# Infos de BCC
BCC_GRID_OPTION = '1'
BCC_PROFESSORS_OPTION = '2'
BCC_DISCIPLINES_OPTION = '3'

BCC_INFOS = {
    BCC_GRID_OPTION: ('GRADE DO CURSO', BCC_GRID_ID),
    BCC_PROFESSORS_OPTION: ('CONTATO DOS PROFESSORES', BCC_PROFESSORS_ID),
    BCC_DISCIPLINES_OPTION: ('DISCIPLINAS', BCC_DISCIPLINES_ID),
    CLOSE_OPTION: ('MENU PRINCIPAL', HOME_ID)
}

# Infos de BSI
BSI_GRID_OPTION = '1'
BSI_PROFESSORS_OPTION = '2'
BSI_DISCIPLINES_OPTION = '3'

BSI_INFOS = {
    BSI_GRID_OPTION: ('GRADE DO CURSO', BSI_GRID_ID),
    BSI_PROFESSORS_OPTION: ('CONTATO DOS PROFESSORES', BSI_PROFESSORS_ID),
    BSI_DISCIPLINES_OPTION: ('DISCIPLINAS', BSI_DISCIPLINES_ID),
    CLOSE_OPTION: ('MENU PRINCIPAL', HOME_ID)
}

# Serviços UFU
SERVICES_RU_OPTION = '1'
SERVICES_INTERCAMPI_OPTION = '2'
SERVICES_LIBRARY_OPTION = '3'
SERVICES_HEALTH_OPTION = '4'

SERVICES = {
    SERVICES_RU_OPTION: ('RESTAURANTE UNIVERSITÁRIO', SERVICES_RU_ID),
    SERVICES_INTERCAMPI_OPTION: ('INTERCAMPI', SERVICES_INTERCAMPI_ID),
    SERVICES_LIBRARY_OPTION: ('BIBLIOTECA', SERVICES_LIBRARY_ID),
    SERVICES_HEALTH_OPTION: ('SERVIÇOS DE SAÚDE', SERVICES_HEALTH_ID),
    CLOSE_OPTION: ('MENU PRINCIPAL', HOME_ID)
}

# Localização
LOCATION_BCC_OPTION = '1'
LOCATION_BSI_OPTION = '2'
LOCATION_DACOMP_OPTION = '3'
LOCATION_ATLETICA_OPTION = '4'
LOCATION_COMPUTARIA_OPTION = '5'
LOCATION_BLOCOS_OPTION = '6'

LOCATIONS = {
    LOCATION_BCC_OPTION: ('SECRETARIA DO CURSO DE CIÊNCIA DE COMPUTAÇÃO', LOCATION_BCC_ID),
    LOCATION_BSI_OPTION: ('SECRETARIA DO CURSO DE SISTEMAS DE INFORMAÇÃO', LOCATION_BSI_ID),
    LOCATION_DACOMP_OPTION: ('DACOMP (DIRETÓRIO ACADÊMICO ALAN TURING)', LOCATION_DACOMP_ID),
    LOCATION_ATLETICA_OPTION: ('ATLÉTICA DA COMPUTAÇÃO', LOCATION_ATLETICA_ID),
    LOCATION_COMPUTARIA_OPTION: ('BATERIA COMPUTARIA', LOCATION_COMPUTARIA_ID),
    LOCATION_BLOCOS_OPTION: ('BLOCOS DE AULAS', CLASSROOMS_ID),
    CLOSE_OPTION: ('MENU PRINCIPAL', HOME_ID)
}

# Localização dos blocos
CLASSROOMS_1B_OPTION = '1'
CLASSROOMS_3Q_OPTION = '2'
CLASSROOMS_5R_OPTION = '3'
CLASSROOMS = {
    CLASSROOMS_1B_OPTION: ('BLOCO 1B.', CLASSROOMS_1B_ID),
    CLASSROOMS_3Q_OPTION: ('BLOCO 3Q.', CLASSROOMS_3Q_ID),
    CLASSROOMS_5R_OPTION: ('BLOCO 5R.', CLASSROOMS_5R_ID),
    CLOSE_OPTION: ('MENU PRINCIPAL.', HOME_ID)
}

# NODES & LEAFS
NODES = {
    HOME_ID: HOME,
    COURSE_INFORMATION_ID: COURSES_MENU,
    UFU_SERVICES_ID: SERVICES,
    LOCATION_ID: LOCATIONS,
    BCC_INFOS_ID: BCC_INFOS,
    BSI_INFOS_ID: BSI_INFOS,
    CLASSROOMS_ID: CLASSROOMS
}

LEAFS = {
    CALENDER_ID: 'LINK PARA CALENDÁRIO ACADÊMICO',
    EVENTS_ID: 'AQUI ESTÃO OS EVENTOS',
    TUTORIALS_ID: 'AQUI ESTÃO OS GUIAS E TUTORIAIS',
    BCC_GRID_ID: 'GRADE DE BCC',
    BCC_PROFESSORS_ID: 'PROFESSORES DE BCC',
    BCC_DISCIPLINES_ID: 'DISCIPLINAS DE BCC',
    BSI_GRID_ID: 'GRADE DE BSI',
    BSI_PROFESSORS_ID: 'PROFESSORES DE BSI',
    BSI_DISCIPLINES_ID: 'DISCIPLINAS DE BSI',
    SERVICES_RU_ID: 'AQUI ESTÃO INFORMAÇÕES DO RESTAURANTE UNIVERSITÁRIO (RU)',
    SERVICES_INTERCAMPI_ID: 'AQUI ESTÃO INFORMAÇÕES SOBRE O INTERCAMPI',
    SERVICES_LIBRARY_ID: 'AQUI ESTÃO INFORMAÇÕES SOBRE A BIBLIOTECA DA UFU',
    SERVICES_HEALTH_ID: 'AQUI ESTÃO INFORMAÇÕES SOBRE SAÚDE NA UFU',
    LOCATION_BCC_ID: 'LOCALIZAÇÃO DA SECRETÁRIA DE BCC',
    LOCATION_BSI_ID: 'LOCALIZAÇÃO DA SECRETÁRIA DE BSI',
    LOCATION_DACOMP_ID: 'LOCALIZAÇÃO DO DIRETÓRIO ACADÊMICO ALAN TURING (DACOMP)',
    LOCATION_ATLETICA_ID: 'LOCALIZAÇÃO DA ATLÉTICA DA COMPUTAÇÃO',
    LOCATION_COMPUTARIA_ID: 'LOCALIZAÇÃO DA BATERIA COMPUTARIA',
    CLASSROOMS_1B_ID: 'LOCALIZAÇÃO DO BLOCO 1B',
    CLASSROOMS_3Q_ID: 'LOCALIZAÇÃO DO BLOCO 3Q',
    CLASSROOMS_5R_ID: 'LOCALIZAÇÃO DO BLOCO 5R'
}
