# Mensagem inicial
INITIAL_MESSAGE = 'OLÁ, EU SOU O UGU! ESTOU AQUI PARA TE AJUDAR!'

# Mensagem de despedida
FAREWELL_MESSAGE = 'ESPERO TER TE AJUDADO!\nVOCÊ QUER FAZER OUTRA PERGUNTA? É SÓ ENVIAR QUALQUER OUTRA MENSAGEM.\nSE SUAS DÚVIDAS FORAM RESOVIDAS, EU TE VEJO EM UMA PRÓXIMA :)'

# Mensagem de opção inválida
INVALID_OPTION = 'OPÇÃO INVÁLIDA! DIGITE UMA OPÇÃO VÁLIDA!'

# Menu ID's
HOME_ID = 1
